name: ✨ Feature Request
description: Suggest a new feature or enhancement for WinScan
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Blockchain Explorer
        - Validators & Staking
        - Governance
        - IBC & Cross-chain
        - PRC20 Tokens
        - EVM Support
        - Wallet Integration
        - UI/UX Improvement
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Really need this
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
